export const items = [
    { title: "Đăng ký học phần", link: "/dang-ky-hoc-phan", cp: "" },
    { title: "Hủy đăng ký học phần", link: "/huy-dang-ky-hoc-phan" },
    { title: "Chuyển lớp học phần", link: "/chuyen-lop-hoc-phan" },
    { title: "Nghỉ học tạm thời", link: "/nghi-hoc-tam-thoi" },
    { title: "Nhập học lại", link: "/nhap-hoc-lai" },
    { title: "Thôi học – Rút hồ sơ", link: "/thoi-hoc-rut-ho-so" },
    { title: "Chuyển ngành", link: "/chuyen-nganh" },
    { title: "Chuyển điểm, miễn học phần sinh viên", link: "/chuyen-diem-mien-hoc-phan-sinh-vien" },
    { title: "Cấp bảng điểm", link: "/cap-bang-diem" },
    { title: "Cấp Giấy chứng nhận hoàn thành khóa học", link: "/cap-giay-chung-nhan-hoan-thanh-khoa-hoc" },
    { title: "Cấp Giấy chứng nhận tốt nghiệp tạm thời", link: "/cap-giay-chung-nhan-tot-nghiep-tam-thoi" },
    { title: "Cấp bản sao bằng tốt nghiệp", link: "/cap-ban-sao-bang-tot-nghiep" },
    { title: "Cấp Giấy xác nhận thời gian học tập", link: "/cap-giay-xac-nhan-thoi-gian-hoc-tap" },
    { title: "Gia hạn thời gian học tập", link: "/gia-han-thoi-gian-hoc-tap" },
    { title: "Chuyển trường", link: "/chuyen-truong" },
    { title: "Xét tốt nghiệp", link: "/xet-tot-nghiep" },
    { title: "Giấy ủy quyền", link: "/giay-uy-quyen" },
    { title: "Cấp Giấy xác nhận vay vốn sinh viên tại địa phương", link: "/cap-giay-xac-nhan-vay-von-sinh-vien-tai-dia-phuong" },
    { title: "Cấp Giấy xác nhận tạm hoãn thi hành nghĩa vụ quân sự", link: "/cap-giay-xac-nhan-tam-hoan-thi-hanh-nghia-vu-quan-su" },
    { title: "Cấp Giấy xác nhận sinh viên học bổng địa phương", link: "/cap-giay-xac-nhan-sinh-vien-hoc-bong-dia-phuong" },
    { title: "Cấp Giấy bổ sung hồ sơ – xác nhận đang học tại Trường", link: "/cap-giay-bo-sung-ho-so-xac-nhan-dang-hoc-tai-truong" },
    { title: "Cấp Giấy giới thiệu để đi thực tập/kiến tập", link: "/cap-giay-gioi-thieu-de-di-thuc-tap-kien-tap" },
    { title: "Cấp giấy xác nhận để giảm trừ gia cảnh (giảm thuế TNCN)", link: "/cap-giay-xac-nhan-de-giam-tru-gia-canh" },
    { title: "Cấp giấy xác nhận xin cấp Visa", link: "/cap-giay-xac-nhan-xin-cap-visa" },
    { title: "Cập nhật thông tin sinh viên", link: "/cap-nhat-thong-tin-sinh-vien" },
    { title: "Cấp lại thẻ sinh viên", link: "/cap-lai-the-sinh-vien" },
    { title: "Miễn giảm học phí", link: "/mien-giam-hoc-phi" },
    { title: "Hoàn học phí/lệ phí", link: "/hoan-hoc-phi-le-phi" }
];